IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_FUNCAO_FUNCIONARIO')
BEGIN
	CREATE TABLE dbo.TB_FUNCAO_FUNCIONARIO
	(
		  FNF_ID INT IDENTITY(1,1) NOT NULL
		, FNF_NOME VARCHAR(40) NOT NULL
		, FNF_STATUS BIT NOT NULL DEFAULT 0

		, CONSTRAINT PK_TB_FUNCAO_FUNCIONARIO_FNF_ID PRIMARY KEY(FNF_ID)
	)
END
GO


IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_FUNCIONARIO')
BEGIN
	CREATE TABLE dbo.TB_FUNCIONARIO
	(
		  FUN_ID INT IDENTITY(1,1) NOT NULL
		, FNF_ID INT NOT NULL --FK
		, FUN_NOME VARCHAR(40) NOT NULL
		, FUN_DIARIA DECIMAL(8,2) NULL
		, FUN_MENSAL DECIMAL(8,2) NULL
		, FUN_DATA_CONTRATACAO DATETIME NULL
		, FUN_STATUS BIT NOT NULL DEFAULT 0
	
		, CONSTRAINT PK_TB_FUNCIONARIO_FUN_ID PRIMARY KEY(FUN_ID)
		, CONSTRAINT FK_TB_FUNCIONARIO_TB_FUNCAO_FUNCIONARIO_FNF_ID FOREIGN KEY(FNF_ID) REFERENCES TB_FUNCAO_FUNCIONARIO
	)
END
GO