IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_OBRA')
BEGIN
	CREATE TABLE dbo.TB_OBRA
	(
		  OBR_ID INT IDENTITY(1,1) NOT NULL
		, OBR_APELIDO VARCHAR(40) NOT NULL
		, OBR_DATA_INICIO DATETIME NOT NULL
		, OBR_DATA_FIM DATETIME NULL
		, OBR_ENDERECO VARCHAR(100) NULL
		, OBR_ORCAMENTO DECIMAL(12,2)
		, OBR_STATUS BIT NOT NULL DEFAULT 0

		, CONSTRAINT PK_TB_OBRA_OBR_ID PRIMARY KEY(OBR_ID)
	)
END
GO

