CREATE TABLE TB_PRODUTO
(
    PRO_ID INT IDENTITY(1,1) NOT NULL,
	PRO_NOME VARCHAR(30) NOT NULL,
	PRO_DESCRICAO VARCHAR(100) NOT NULL,
	PRO_PRECO DECIMAL(10,2) NOT NULL,
	PRO_SITUACAO BIT NOT NULL,
	CAT_ID INT NOT NULL,

	CONSTRAINT pk_TB_PRODUTO_ID PRIMARY KEY CLUSTERED(PRO_ID),
	CONSTRAINT FK_TB_CATEGORIA_ID FOREIGN KEY(CAT_ID) REFERENCES TB_CATEGORIA
);

GO