CREATE TABLE TB_PRODUTO
(
    ProId INT IDENTITY(1,1) NOT NULL,
	ProNome VARCHAR(30) NOT NULL,
	ProDescricao VARCHAR(100) NOT NULL,
	ProPreco DECIMAL(10,2) NOT NULL,
	ProSituacao BIT NOT NULL,
	CatId INT NOT NULL,

	CONSTRAINT pk_TB_PRODUTO_ID PRIMARY KEY CLUSTERED(ProId),
	CONSTRAINT FK_TB_CATEGORIA_ID FOREIGN KEY(CatId) REFERENCES TB_CATEGORIA
);

GO